version: "3.5"
services:
  bmstusa-app:
    image: sarpol/server:latest
    env_file: .env
    restart: unless-stopped
    command: "./server"
    volumes:
      - images-storage:/app/static/images
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - event
      - user

  auth:
    image: sarpol/auth:latest
    env_file: .env
    restart: unless-stopped
    command: "./auth"
    ports:
      - "8081:8081"
    depends_on:
      - redis-db

  event:
    image: sarpol/event:latest
    env_file: .env
    restart: unless-stopped
    command: "./event"
    volumes:
      - images-storage:/app/static/images
    ports:
      - "8083:8083"

  user:
    image: sarpol/user:latest
    env_file: .env
    restart: unless-stopped
    command: "./user"
    volumes:
      - images-storage:/app/static/images
    ports:
      - "8084:8084"
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./pkg/prometheus:/etc/prometheus"
    depends_on:
      - bmstusa-app
  
  redis-db:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      
# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
    external: true
  pgdata:
  images-storage:
    driver: local    
    driver_opts:       
      o: bind       
      type: none       
      device: /home/ubuntu/static/images