name: StartApp

env:
  SERVER_TAG: latest
  AUTH_TAG: latest
  EVENT_TAG: latest
  USER_TAG: latest

on:
  push:
  pull_request:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/bmstusa/backend
            sudo docker volume create --name=grafana-storage
            git pull
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker rmi $(docker images -q)