name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Coverage
        run: go test -cover -coverprofile=cover.out -coverpkg=./... ./...
      - name: Exclude directories
        run: cat cover.out | fgrep -v "main.go" | fgrep -v "mock.go" | fgrep -v "pb.go" | fgrep -v "response_easyjson.go" > cover1.out

      - name: Create badge
        run: |
          total=`go tool cover -func=cover1.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$total <= 40" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$total > 60" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > tests.svg